name: Deploy to Vercel

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name:  Install dependencies
        run: npm install



      - name:  Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm \
            --org team_7zWoGwKtcYzHFUU542wE5A89 \
            --project prj_BMkAxkzAhehOmr3quatJofxN6Njx
